### ISSUE TITLE
Patron de diseño Observer

### ISSUE THREAD

**Issue by rarivera14** [mitogh/dice-game#36]
Buenas noches hemos revisado si codigo y observamos que usted puede utilizar un patron de diseño Observer lo que cual permitira no tener que manejar el metodo internamente en su codigo, ya que una observer se encargara de actualizar el puntaje
Aqui adjunto el diagrama uml del antes y despues:
Antes:
![image](https://user-images.githubusercontent.com/61158266/89600569-f725df80-d827-11ea-8ec7-dd3b9cf4d8dc.png)
Despues:
![image](https://user-images.githubusercontent.com/61158266/89600580-fb51fd00-d827-11ea-8028-8ac77e4445f2.png)

**Comment by mitogh** [comment]
Hola @rarivera14 

Muchas gracias, claro es una excelente sugerencia, existen diferentes mejoras por hacer la implementación inicial fue solo un MVP. 

Pero si tienes algún cambio que quieras hacer con mucho gusto puedes enviar un PR o hacer un fork de este MVP.

Gracias de nuevo, excelente fin de semana.
